# Generated by Django 4.0.3 on 2022-04-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
