# Form implementation generated from reading ui file 'audio_Form.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_audio_Form(object):
    def setupUi(self, audio_Form):
        audio_Form.setObjectName("audio_Form")
        audio_Form.resize(665, 412)
        self.formLayout = QtWidgets.QFormLayout(audio_Form)
        self.formLayout.setObjectName("formLayout")
        self.graphicsView = QChartView(audio_Form)
        self.graphicsView.setObjectName("graphicsView")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.graphicsView)

        self.retranslateUi(audio_Form)
        QtCore.QMetaObject.connectSlotsByName(audio_Form)

    def retranslateUi(self, audio_Form):
        _translate = QtCore.QCoreApplication.translate
        audio_Form.setWindowTitle(_translate("audio_Form", "Form"))
from PyQt6.QtCharts import QChartView
